### ISSUE TITLE
install iRODS on dev-immcellfie 

### ISSUE THREAD

**Issue by LauraCapps** [RENCI/fuse-immcellfie#15]
( [Project Plan](http://bit.ly/imcellfiepplan) )
**Which deliverable?**

**Which repos (e.g., tx-logging)?**
Repo - immcellfie-api
**Short name**

**Description**
install iRODS on dev-immcellfie
**Related tickets**

**Steps to close this ticket**
Close ticket when... @krobasky to fill in steps to close.

**Comment by xu-hao** [comment]
irods installed on dev-immcellfie
