### ISSUE TITLE
Feature requests for Dashboard on Stage: Clarify "download", "task" 

### ISSUE THREAD

**Issue by krobasky** [RENCI/fuse-immcellfie#43]
Upload/Download is confusing because we "upload" from our computer to ImmCellfie, but we "download" data from immunespace into immcellfie, and we also "download" data from ImmCellfie. Task/output" is also confusing because we use it to mean 

On the "Data Source" -> "Immunespace" screen (see below): 
 - [x] Replace 'Download ID' with 'Dataset ID'
 - [x] Replace 'CellFIE tasks' with 'CellFIE runs'
 - [x] Replace 'Load new....' with 'Retrieve new...' on the screen & popup
![image](https://user-images.githubusercontent.com/413166/150008827-d1d89346-c3b7-41a1-b630-481970962bd5.png)
On the "Data Source" -> "Data upload" screen (see below):
 - [x] Suggestion: Replace "Data upload" with "My computer" (or similar)
![image](https://user-images.githubusercontent.com/413166/150011596-1a80f239-89e0-49ac-bde9-e294e28eebc7.png)
On the "CellFIE" -> "Select CellFIE Task" panel (see below):
 - [x] Replace "Select CellFIE Task" with "Select CellFIE Run"
 - [ ] Replace "uploaded data" with "retrieved data"
 - [ ] Replace "task_id:" with "run_id"
![image](https://user-images.githubusercontent.com/413166/150011961-e501e6ef-076b-456b-ae01-f906e16fb554.png)
On the "CellFIE" -> "CellFIE Output Visualizations" panel (see below):
 - [ ] Replace "CellFIE Output Visualizations" with "CellFIE Run Output Visualizations"
 - [x] Replace "Task started" with "Run started"
![image](https://user-images.githubusercontent.com/413166/150012170-964eaccd-3bf6-4111-8f2b-fad2c48b10ea.png)
On the top navigation bar (see below):
 - [ ] Suggestion: Replace 'Input data' with 'Loaded Dataset'
![image](https://user-images.githubusercontent.com/413166/150026774-3c8fe34f-77e0-4d66-8638-db8046ded51c.png)
On 'Downloads' page (see below):
 - [ ] Suggestion: Replace 'CellFIE output' with 'CellFIE Run output'
 - [ ] Suggestion: Remove 'Phenotype data' and 'Expression data'? - I'm not sure we have license to repackage serve the data we retrieve from immunespace.
![image](https://user-images.githubusercontent.com/413166/150026895-53cbb413-3370-48b9-9ef2-663d1f82537b.png)

**Comment by davidborland** [comment]
I've implemented some of these. We can discuss the others. 

Regarding the data download: if we are not going to enable downloading the phenotype and expression data (note that these are still available via the API if users really want it...), should we just remove the Download Data page and move the download CellFIE output button to the CellFIE output panel?

**Comment by krobasky** [comment]
@LauraCapps let's add this to the agenda for discussion with Immunespace guys: "can we allow users to download the data they import and transform from Immunespace"

@davidborland ... "import" is a good word, if you want to use that instead of "retrieve" - I see you've already made the changes to "retrieve", so its your call if you want to change it again. Either seems good to me.

David, one more:
- [ ] Suggest replace "No CellFIE output" with "No CellFIE run output"
![image](https://user-images.githubusercontent.com/413166/150159999-c2700703-a331-480f-9140-f0c0d5104dcc.png)

**Comment by davidborland** [comment]
I like import. Will go with that for now. I'm less inclined to CellFIE run output in the various places, as it is more verbose, and I think CellFIE output works on its own. We can discuss though.

**Comment by krobasky** [comment]
I agree with you, but "CellFIE output" doesn't seem quite right, it doesn't indicate that each run has its own output, and it doesn't generalize well to other tools like PCA. How about "CellFIE resultset"? Then you might also have "PCA resultset", and you might somehow indicate the run_id that resultset is tied to, in case you want to check the parameters and dataset you used or something.

**Comment by davidborland** [comment]
- [ ] Remove "Data source"
- [x] Rename to CellFIE Run Results, perhaps with subtitle explaining in more detail
- [x] Move Download to Results page
- [x] Dataset selection
- [x] Rename "import" to "retrieve"

**Comment by krobasky** [comment]
Glossary of terms from this ticket disucssion:
 - data source: upload file, Immunespace, example data, etc. 
 - dataset: set of data used for input to a tool run where the tool can be cellfie or something else. There's multiple datasets per 
 -  datasource, and multiple runs per dataset
 - run: formerly, 'task', is the job associated with a tool, a dataset, a distinct set of parameters, and ultimatelly, a redis job. There' 
 - can be multiple instances of the same run parameters, one per redis job
 - resultset: one resultset per run, used for visualizations
 - 
We need to capture this in a google to allow it to evolve and drive any necessary changes to the API

**Comment by krobasky** [comment]
@davidborland I captured the above in the txscience co-work team meetings, we can add/modify it from there

https://docs.google.com/document/d/1UBQmzMnQvjfAD_nl9SKDimW0bcSOFv2BV1ncP4XWWH0/edit

**Comment by davidborland** [comment]
Implemented
